version: '3.8'

services:
  centralized-auth:
    image: ghcr.io/ttolyanich/centralized-auth:latest
    build: .
    container_name: centralized-auth
    restart: unless-stopped
    ports:
      - "${BIND_HOST:-127.0.0.1}:${BIND_PORT:-5001}:${BIND_PORT:-5001}"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: gunicorn --workers 2 --bind 0.0.0.0:${BIND_PORT:-5001} app:app
